🚧Add Zahlenraten
MarcRaeder/ZahlenratenStudio2.0 pull request #1
Opened 2023-01-26 15:06 UTC by MarcRaeder

2023-02-02 13:06 UTC, stefanluth commented
`make run` returns this for me:

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/80166473/216332950-86283881-a68f-4f57-bc4a-8f7380e7545a.png">

2023-02-02 13:13 UTC, stefanluth commented
<img width="668" alt="image" src="https://user-images.githubusercontent.com/80166473/216334205-fcb20bad-19ea-4413-9ca2-7ffb536d6a58.png">

Unnecessarily long data output associations (arrows) :) Also, try to use right angles :P

2023-02-06 08:31 UTC, stefanluth requested changes

2023-02-06 08:31 UTC, stefanluth commented on Zahlenraten.Intermediate/apps/Zahlenraten.Intermediate/frontend/src/ZahlenratenCustomForm/ZahlenratenCustomForm.tsx
> +        <h1>Du hast noch {this.props.userTask.tokens[0].payload.leftTries} Versuche</h1>
```suggestion
      <div className='test-class'>
        <h1>Du hast noch {this.props.userTask.tokens[0].payload.leftTries} Versuche</h1>
```

2023-02-06 08:31 UTC, stefanluth commented on Zahlenraten.Intermediate/apps/Zahlenraten.Intermediate/frontend/src/ZahlenratenCustomForm/ZahlenratenCustomForm.tsx
> +        <h1>Du hast noch {this.props.userTask.tokens[0].payload.leftTries} Versuche</h1>
You use `this.props.userTask.tokens[0].payload` a lot, you could move it to a variable :)

2023-02-06 08:31 UTC, stefanluth commented on Zahlenraten.Intermediate/apps/Zahlenraten.Intermediate/frontend/src/ZahlenratenCustomForm/ZahlenratenCustomForm.tsx
> +  private userInput: React.RefObject<HTMLInputElement>;
```suggestion
export class ZahlenratenCustomForm extends React.Component<CustomFormProps> {
  private userInput: React.RefObject<HTMLInputElement>;
```

2023-02-06 08:31 UTC, stefanluth commented on Zahlenraten.Intermediate/apps/Zahlenraten.Intermediate/frontend/src/ZahlenratenCustomForm/ZahlZuNiedrigCustomForm.tsx
> +  private guess;
```suggestion
export class ZahlZuNiedrigCustomForm extends React.Component<CustomFormProps> {
  private guess;
```

2023-02-06 08:31 UTC, stefanluth commented on Zahlenraten.Intermediate/apps/Zahlenraten.Intermediate/frontend/src/ZahlenratenCustomForm/ZahlZuHochCustomForm.tsx
> +  constructor(props: CustomFormProps) {
```suggestion
export class ZahlZuHochCustomForm extends React.Component<CustomFormProps> {
  private guess;
  private randomNumber;
  private text;
  private range;
  private tries;
  private distance;

  constructor(props: CustomFormProps) {
```

2023-02-06 08:31 UTC, stefanluth commented on Zahlenraten.Intermediate/apps/Zahlenraten.Intermediate/frontend/src/ZahlenratenCustomForm/ZahlZuNiedrigCustomForm.tsx
> +  constructor(props: CustomFormProps) {
```suggestion
  private distance;

  constructor(props: CustomFormProps) {
```

2023-02-06 08:31 UTC, stefanluth commented on Zahlenraten.Intermediate/apps/Zahlenraten.Intermediate/frontend/src/ZahlenratenStartDialog/ZahlenratenStartdialog.tsx
> +  constructor(props: StartDialogProps) {
```suggestion
export class ZahlenratenStartDialog extends React.Component<StartDialogProps> {
  private userName: React.RefObject<HTMLInputElement>;
  private lowestNumber: React.RefObject<HTMLInputElement>;
  private highestNumber: React.RefObject<HTMLInputElement>;

  constructor(props: StartDialogProps) {
```

2023-02-06 09:03 UTC, stefanluth approved these changes

2023-02-10 10:38 UTC, DevBastiS requested changes
build folder in frontend should be ignored.
Otherwise this looks really good.

2023-02-13 07:48 UTC, DevBastiS approved these changes

2023-02-13 07:54 UTC, merged